name: Check for DOMPurify updates

on: workflow_dispatch

jobs:
  checkdepedencies:
    runs-on: ubuntu-latest
    steps:
      # Checkout toolbox
      - name: checkout
        uses: actions/checkout@v2
      # Download latest DOMPurify
      - name: download
        id: download
        uses: creesch/github-latest-release-zip@main
        with:
          owner: cure53
          repo: DOMPurify
          downloadPath: test/whatever/path
      # Unzip and copy over the release purify.js if there is an update this will create a delta.
      - name: unzip
        run: |
          BASEDIR=$(pwd)
          cd test/whatever/path
          FILENAME="${{ steps.download.outputs.filename }}"
          unzip $FILENAME
          DIRECTORY=$(ls -d */)
          echo $DIRECTORY
          cp "${DIRECTORY}dist/purify.js" "${BASEDIR}/purify.js"
      # Run pullrequest action, if the previous stepped caused no difference no pullrequest will be made.
      - name: pullrequest
        uses: peter-evans/create-pull-request@v3
        with: 
          commit-message: Update DOMPurify to ${{ steps.download.outputs.tag_name }}
          title: Update DOMPurify to ${{ steps.download.outputs.name }}
          body: |
            [${{ steps.download.outputs.name }}](${{ steps.download.outputs.html_url }})
            
            ## Release notes: 

            ${{ steps.download.outputs.body }}
          branch: update-DOMPurify-dependency
          delete-branch: true
