name: Check for DOMPurify updates

# Controls when the action will run. 
on: workflow_dispatch

jobs:
  checkdepedencies:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: download
        id: download
        uses: creesch/github-latest-release-zip@main
        with:
          owner: cure53
          repo: DOMPurify
          downloadPath: test/whatever/path
      - name: unzip
        run: |
          BASEDIR=$(pwd)
          cd test/whatever/path
          FILENAME="${{ steps.download.outputs.filename }}"
          unzip $FILENAME
          DIRECTORY=$(ls -d */)
          echo $DIRECTORY
          cp "${DIRECTORY}dist/purify.js" "${BASEDIR}/purify.js"
      - name: pullrequest
        uses: peter-evans/create-pull-request@v3
        with: 
          commit-message: Update dompurify dependencies
          title: Update dompurify dependencies
          body: this is a test
          branch: update-dompurify-dependencies
